### ISSUE TITLE
Fullstack-project review

### ISSUE THREAD

**Issue by ShootingStar91** [AndrewTrieu/chathive#1]
# Fullstack-project review 

This is a review of your Fullstack practice project. You may apply the suggestions presented here if you so wish, but you do not have to implement any further changes to receive the credits for your project.

### What did I do

+ I opened the webpage and attempted to register
+ I logged in with the given test credentials
+ I attempted to push different buttons
+ I browsed the existing posts
+ I created a new post
+ I opened the views of the test user and other users
+ I liked posts

### Feedback on the user experience

+ The website looks smooth and professional, good work on the UI
+ The UI is also responsive and works on a mobile-size display, great job
+ Very small improvements will make it even better, such as adding padding/margin to make the text not touch the borders of it's containers
+ The 'infinite scroll' of the post feed works very well
+ Although the website is a work in progress with it's missing features, it looks like a great start

### Feedback on the code

+ The frontend is mostly organized into reasonable files and components, and the code is clear and readable.
+ The return-part in navbar/index.jsx is a bit long. Usually, when comments have to clarify the code structure, it is a sign that things should be separated into smaller functions or components.
+ The getUser-function that fetches the user from the server, and the state management related to that is repeated in multiple different components. This could be handled via a custom hook, or a library like ReactQuery or RTK Query. This would reduce the user query handling into just one line while it would also prevent sending the request again if the user was already on the frontend.
+ External libraries like Redux, MaterialUI and redux-persist are used to simplify and enhance the code
+ Backend code is good and readable also, and organized reasonably to separate logic
+ Middlewares are used and jsonwebtoken handles the login in a smart way
+ Overall, the code is good, readable and well-organized

The application is solid work and a great start. Good work!

**Comment by AndrewTrieu** [comment]
Thank you! This is a very comprehensive and detailed feedback! I will apply these changes in thr future when I have time.
